title: Vladimiras Malyskinas | Portfolio
baseURL: ""
theme: PaperModX

enableRobotsTXT: true
enableEmoji: true

params:
  description: "A collection of work by me!"
  author: Vladimiras Malyskinas
  images:
    - cover.png
  favicon: knobs.ico
  #logo:
  #  icon: images/logo.svg
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:
    - posts
    - notes

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: false
  ShowWordCount: false
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: malvladimiras+website@gmail.com

  socialIcons:
    - name: telegram-simple
      url: "https://t.me/vladimirasmal"
    - name: gmail
      url: email
    - name: fiverr-simple
      url: "https://www.fiverr.com/trxlhxds"
    - name: linkedin-simple
      url: "https://www.linkedin.com/in/vladimirasmal"

  homeInfoParams:
    Title: |
      BSc Music Technology

      Game Audio & Acoustics
    Content: |
      Welcome to my little portfolio, where you can find my:

      - **Social Links**

      - **Previous Work**

      - **Blog Posts**

      - **_Hopefully Soon_ Useful Tools**

      Why not check out my <ins>[work](/portfolio/work/)</ins>?

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: posts
      url: /posts/
      weight: 2
    - name: contact
      url: /contact/
      weight: 3

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
