title: Vladimiras Malyskinas | Portfolio
baseURL: ""
theme: PaperModX

enableRobotsTXT: true
enableEmoji: true

params:
  description: "A collection of my work!"
  author: Vladimiras Malyskinas
  images:
    - cover.png
  favicon: knobs.ico
  #logo:
  #  icon: images/logo.svg
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: false
  ShowWordCount: false
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: malvladimiras+website@gmail.com

  socialIcons:
    - name: telegram-simple
      url: "https://t.me/vladimirasmal"
    - name: gmail
      url: email
    - name: fiverr-simple
      url: "https://www.fiverr.com/trxlhxds"
    - name: linkedin-simple
      url: "https://www.linkedin.com/in/vladimirasmal"

  homeInfoParams:
    Title: |
      About Vladimiras...
    Content: |
      Welcome to my portfolio, where you can find:

      - <ins>[**My Work:**](/work/)</ins>

        - <ins>[**Acoustics**](/work/acoustics/)</ins>
        - <ins>[**Game Audio**](/work/auris-media-portfolio/)</ins>
        - <ins>[**Sound Design**](/work/sound-design/)</ins>

      - <ins>[**Blog Posts**](/posts/)</ins>

      - <ins>[**Play My New Game**](/work/samurai-game/)</ins>

      If you are here for <mark>coding lessons</mark> - [**Click Here!**](/coding-lessons/) 

      And here are my contact links:

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: posts
      url: /posts/
      weight: 2
    - name: coding lessons
      url: /coding-lessons/
      weight: 4
    - name: contact
      url: /contact/
      weight: 4

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
